config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  scope(controller: :registration) do
    post 'register', action: :register, as: :registration
  end

  scope(controller: :assignments) do
    get 'assignments/by_lti_id/:lti_assignment_id', action: :show_by_lti_id
    post 'assignments/configure', action: :configure, as: :assignment_configuration
    post 'assignments/:lti_assignment_id/update', action: :update, as: :assignment_update
  end

  scope(controller: :tool_proxy) do
    get 'tool_proxy/obtain_guid/:proxy_id', action: :show_guid_by_id
    get 'tool_proxy/obtain_guid/assignment/:assignment_tc_id', action: :show_guid_by_assignment_tc_id
  end

  scope(controller: :submissions) do
    get 'tool_proxy/:tool_proxy_guid/submissions/:tc_submission_id/retrieve',
        action: :retrieve_and_store, as: :submission_retrival
    get 'submission/by_tc_id/:tc_submission_id', action: :show_by_tc_id
    post 'submission/index', action: :index
  end

  scope(controller: :originality_reports) do
    post 'assignments/:assignment_tc_id/submissions/:submission_tc_id/originality_report',
         action: :create, as: :originality_create
    put 'assignments/:assignment_tc_id/submissions/:submission_tc_id/originality_report/:or_tc_id',
         action: :update, as: :originality_update
  end

  namespace :event do
    post :submission
  end
end

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="display-4">LTI Originality Example Tool</h1>
    <p>This is an example LTI 2 implementation of the Canvas Originality Reporting Framework </p>

  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <h2>Installing</h2>
    <p>To install the tool, copy the registration link below and paste it into the LTI 2 Registration box in canvas</p>
    <p><input class="form-control" type="text" value="<%= registration_url %>" readonly></p>
  </div>

  <div class="col-md-6">
    <h2>Source Code</h2>
    <p>The source code for this project can be found on <a href="https://github.com/instructure/lti_originality_report_example">GitHub</a></p>
  </div>
</div>